# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Yoda\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_EVENT_CREATE, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_database_users:
            entity: { class: UserBundle:User }

    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login_form
            logout:
                path:   logout
                target: event_index
            remember_me:
                secret: "Order 1138"
            anonymous: ~
            switch_user: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }